# Generated by Django 5.0.7 on 2024-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='         ', max_length=9)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('player_x_name', models.CharField(default='Player X', max_length=50)),
                ('player_o_name', models.CharField(default='Player O', max_length=50)),
                ('player_x_wins', models.IntegerField(default=0)),
                ('player_o_wins', models.IntegerField(default=0)),
                ('ai_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
